version: 0.1

env:
  variables:
    S3_BUCKET: "sam-demo-arun"

phases:

  install:
    commands:
      - pip install pytest

  pre_build:
    commands:
      - pytest

  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file serverless-output.yaml

artifacts:
  type: zip
  files:
    - serverless-output.yaml
